apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - image: lmapwns/argocd-image-uploader-test:{{ .Values.imageTag }}
          name: test
      restartPolicy: Never